package com.freelance.www.base.util;

public enum StatusCodeEnum {
    API_COMMON_INF_OK, API_COMMON_ERR_ERROR, API_COMMON_ERR_PARAM, API_COMMON_ERR_DB_EXCEPTION, API_COMMON_ERR_DB_EXIST, API_COMMON_ERR_FILE_UPLOAD_FAILED, API_COMMON_ERR_DOWNFILE_FAILED, API_COMMON_ERR_SERVER_ERROR, API_COMMON_ERR_DB_SQL_EXCEPTION, API_COMMON_ERR_DB_ACCESS_EXCEPTION, API_COMMON_ERR_MISSING_REQUEST_PARAM, API_COMMON_ERR_NOT_READABLE_REQUEST_PARAM, API_COMMON_ERR_NOT_VALID_REQUEST_PARAM, API_COMMON_ERR_BIND_REQUEST_PARAM, API_COMMON_ERR_NOT_VALID_PARAM, API_COMMON_ERR_NO_HANDLER_FOUND, API_COMMON_ERR_METHOD_NOT_SUPPORTED, API_COMMON_ERR_MEDIA_TYPE_NOT_SUPPORTED, API_COMMON_ERR_NOT_VALID_CRON_PARAM, API_COMMON_ERR_NOT_VALID_CLASS_PARAM, API_COMMON_ERR_MAX_JOB;

    public String getStatusCode() {
        return name().replace("_", "-");
    }
}
